pipeline-folder: "/users/fischerd/git/Pipeline-Metagenome"
pipeline-config: "/scratch/project_2006153/CO2/Pipeline-Metagenome_config.yaml"
project-folder: "/scratch/project_2006153/CO2"                                               # Path to the project folder
rawdata-folder: "/scratch/project_2006153/CO2/FASTQ/RAW" 
server-config: "/users/fischerd/git/Pipeline-Metagenome/Pipeline-Metagenome_server_config.yaml"
samplesheet-file: "/scratch/project_2006153/CO2/samplesheet.tsv"
local-scratch: $LOCAL_SCRATCH
tmp: "/scratch/prject..."
contamination-folder: "/scratch/project_2006153/CO2/Contamination/"
contamination-refs: ["ARS-UCD1.2_Btau5.0.1Y.fa"]

urls:
    host: ""

params:
  fastp:
    trim_front1: 12
    trim_tail1: 0
    trim_front2: 0
    trim_tail2: 0
  fastqc:
    threads: 20
  megahit:
    kmin: 31          
  star:
    overhang: 149
    limitGenomeGenerateRAM: 300647710720
  concoct:
    maxClusters: 4000
    bedcut: 10000000
